
###
# Ollama list all models
GET http://localhost:11434/v1/models

###
# LM Studio list all models
GET http://localhost:1234/v1/models


###
# LLM Gateway list all models
GET http://localhost:8008/v1/models
Authorization: Bearer llmgw-ZHXiMOKLVrD-a6roXT1pf-DE1XZFJDjp

###
# Extention Backend list all models
GET http://localhost:8000/v1/models
